{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zomboid-server.fullname" . }}-config
  labels:
    {{- include "zomboid-server.labels" . | nindent 4 }}
data:
  {{- range $filename, $content := .Values.config }}
  {{ $filename }}: |
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
